yarnPath: '.yarn/releases/yarn-berry.cjs'
lockfileFilename: .yarn/yarn.lock

logFilters:
  - code: YN0000
    level: discard
  - code: YN0002
    level: discard
  - code: YN0013
    level: discard
  - code: YN0060
    level: discard

nodeLinker: pnp
